#!/usr/bin/env python3
# from typing import *

YES = 'Yes'
NO = 'No'

# def solve(T: str, U: str) -> str:
def solve(T, U):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    T = input()
    U = input()
    a = solve(T, U)
    print(a)

if __name__ == '__main__':
    main()
