#!/usr/bin/env python3
# from typing import *



# def solve(Q: int, T: List[int], S: List[str]) -> List[str]:
def solve(Q, T, S):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    Q = int(next(tokens))
    T = [None for _ in range(Q)]
    S = [None for _ in range(Q)]
    for i in range(Q):
        T[i] = int(next(tokens))
        S[i] = next(tokens)
    assert next(tokens, None) is None
    a = solve(Q, T, S)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
