#!/usr/bin/env python3
# from typing import *



# def solve(Q: int, y: List[int]) -> List[str]:
def solve(Q, y):
    pass  # TODO: edit here

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    Q = int(input())
    y = [None for _ in range(Q)]
    for i in range(Q):
        y[i] = int(input())
    a = solve(Q, y)
    for i in range(Q):
        print(a[i])

if __name__ == '__main__':
    main()
